AllCops:
  Exclude:
    - '*.gemspec'
    - 'build/**/*'
    - 'download/**/*'
    - Vagrantfile
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Max: 15

Security/YAMLLoad:
  Exclude:
    - script/livecheck

Style/AccessorGrouping:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/DoubleNegation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/HashConversion:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SignalException:
  EnforcedStyle: semantic

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
