#!/usr/bin/env bash

set -xe

MAKE_COMMAND='make all test -j'

for arch in i386 x86_64; do
  $MAKE_COMMAND ARCH=$arch
done

for vm in linux_{i686,x86_64}; do
  vagrant up $vm
  vagrant ssh $vm -c "cd /vagrant; $MAKE_COMMAND"
  vagrant halt
done
