#!/usr/bin/env ruby

# Feed Makefile to this script to set all variables XXX_VER to latest versions

require 'English'

ARGF.map do |line|
  if (name = line[/^([A-Z]+)_VER *:= *.*/, 1])
    Thread.new do
      version = `script/livecheck --bare #{name}`.strip
      abort unless $CHILD_STATUS.success?
      "#{name}_VER := #{version}\n"
    end
  else
    line
  end
end.each do |out|
  if out.respond_to?(:value)
    $stderr << out.value unless $stdout.tty?
    $stdout << out.value
  else
    $stdout << out
  end
end
