#!/usr/bin/env bash

present(){
  local missing=0
  for name in "$@"; do
    if command -v "$name" >/dev/null 2>&1; then
      echo "got $name"
    else
      echo "no $name"
      missing=1
    fi
  done
  [ $missing -eq 0 ] || return 127
}

if ! present make wget gcc g++ chrpath perl pkg-config automake; then
  if present apt-get; then
    apt-get -y install make wget gcc g++ chrpath perl pkg-config automake
  elif present yum; then
    yum -y install make wget gcc gcc-c++ chrpath perl pkg-config automake
  else
    echo 'unknown package manager'
    exit 1
  fi
fi

if ! make --version 2>&1 | grep -q 'GNU Make'; then
  echo 'non gnu make'
  exit 1
fi
