name: cache-downloads
on:
  schedule:
  - cron: 7 10 */3 * *
  workflow_dispatch:
    inputs:
      retry:
        description: 'Retry attempt'
        required: true
        type: number
jobs:
  cache-downloads:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
      with:
        ruby-version: '4'
        bundler-cache: true
    - id: cache-restore
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: download
        key: download-${{ hashFiles('checksums.mk') }}
        restore-keys: download-
    - run: make download-tidy-up
    - run: make download
    - run: make download-dependencies
    - uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: download
        key: download-${{ hashFiles('checksums.mk') }}
      if: steps.cache-restore.outputs.cache-hit != 'true'
    - run: make purge-dependencies
    - env:
        RETRY: ${{ inputs.retry }}
        RETRIES: 3
        GITHUB_TOKEN: ${{ secrets.RETRY_TOKEN }}
      run: |
        make update-versions || {
          exit_code=$?
          if (( ${RETRY:-0} < $RETRIES )); then
            sleep $(( ($RETRY + 0) * 30 ))
            gh workflow run "$GITHUB_WORKFLOW" --repo "$GITHUB_REPOSITORY" --ref "$GITHUB_REF_NAME" -f retry=$(( $RETRY + 1 ))
          else
            exit $exit_code
          fi
        }
    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: download
        key: download-${{ hashFiles('checksums.mk') }}
        lookup-only: true
