name: check
on:
  push:
  pull_request:
  schedule:
  - cron: 45 4 * * 0
permissions: {}
jobs:
  check:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-22.04-arm
        - macos-15-intel
        - macos-14
        ruby:
        - '2.7'
        - '3.2'
        - '3.3'
        - '3.4'
        - '4.0'
        - jruby-9.4
        - jruby-10.1
      fail-fast: false
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - run: make test
    - run: bundle exec image_optim --info
    - run: bundle exec rspec
