name: docker-build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        params:
        - ''
        - DOCKER_FILE=Dockerfile.debian DOCKER_TAG_SUFFIX=-debian
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
    - run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          echo "MAKE_ACTION=docker-push" >> $GITHUB_ENV
        else
          echo "MAKE_ACTION=docker-test" >> $GITHUB_ENV
        fi
    - run: make "$MAKE_ACTION" ${{ matrix.params }}
