name: livecheck
on:
  push:
  pull_request:
  schedule:
  - cron: 34 5 * * *
  workflow_dispatch:
    inputs:
      retry:
        description: 'Retry attempt'
        required: true
        type: number
jobs:
  livecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '4'
        bundler-cache: true
    - env:
        RETRY: ${{ inputs.retry }}
        RETRIES: 3
        GITHUB_TOKEN: ${{ secrets.RETRY_TOKEN }}
      run: |
        script/livecheck || {
          exit_code=$?
          if (( $exit_code == 2 )) && (( ${RETRY:-0} < $RETRIES )); then
            sleep 300
            gh workflow run "$GITHUB_WORKFLOW" --repo "$GITHUB_REPOSITORY" --ref "$GITHUB_REF_NAME" -f retry=$(( $RETRY + 1 ))
          else
            if (( $exit_code == 1 )); then
              gh workflow run cache-downloads --repo "$GITHUB_REPOSITORY" --ref "$GITHUB_REF_NAME" -f retry=0
            fi
            exit $exit_code
          fi
        }
