name: livecheck
on:
  push:
  pull_request:
  schedule:
  - cron: 34 5 * * *
  workflow_dispatch:
    inputs:
      retry:
        description: 'Retry attempt'
        required: true
        type: number
jobs:
  livecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
        bundler-cache: true
    - env:
        RETRY: ${{ inputs.retry }}
        RETRIES: 10
        GITHUB_TOKEN: ${{ secrets.RETRY_TOKEN }}
      run: |
        bundle exec script/livecheck || {
          exit_code=$?
          if (( $exit_code == 2 )) && (( ${RETRY:-0} < $RETRIES )); then
            sleep 300
            gh workflow run livecheck --repo $GITHUB_REPOSITORY --ref $GITHUB_REF_NAME -f retry=$(( $RETRY + 1 ))
          else
            exit $exit_code
          fi
        }
