name: livecheck
on:
  schedule:
  - cron: 34 5 * * *
jobs:
  livecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 10
        retry_wait_seconds: 60
        command: bundle exec make livecheck
